[project]
name = "sor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cupy-cuda13x>=13.6.0",
    "gdspy>=1.6.13",
    "ipykernel>=7.0.1",
    "matplotlib>=3.10.7",
    "nbformat>=5.10.4",
    "numba>=0.62.1",
    "numpy>=2.3.4",
    "plotly>=6.4.0",
    "pytest>=8.4.2",
    "pyyaml>=6.0.3",
    "scipy>=1.11.0",
    "shapely>=2.1.2",
]

[dependency-groups]
dev = [
    "ruff>=0.14.1",
    "scalene>=1.5.0",
    "snakeviz>=2.2.2",
]
