# Configuration file for SOR Poisson solver
# Si/SiO2 system with finger gate structure
#
# New coordinate system:
# z = 0nm (surface, electrodes)
# z-axis extends in negative direction
#
# Structure:
# z = 0nm: Surface (electrodes)
# ---------------
# SiO2 (0nm to -10nm)
# ---------------
# Si  (-10nm to -50nm)
# ---------------

# Computational domain
domain:
  size: [100e-9, 100e-9, 100e-9]  # [x, y, z] in meters (100nm x 100nm x 100nm)
  grid_spacing: 1e-9  # h in meters (1nm, isotropic grid)

# Material layer structure
# z_range format: [z_max, z_min] where z_max > z_min
layers:
  - material: "SiO2"
    z_range: [0, -20e-9]  # 0nm → -10nm: Silicon oxide layer (surface side)
    epsilon_r: 3.9

  - material: "Si"
    z_range: [-20e-9, -100e-9]  # -10nm → -100nm: Silicon substrate (bottom side)
    epsilon_r: 11.7

# Electrode structure (multiple finger gates)
# z_position: electrode bottom position (negative value)
# Electrode extends from z_position to z=0 (surface)
electrodes:
  - name: "finger_gate_1"
    shape: "rectangle"
    x_range: [10e-9, 30e-9]  # 10-30nm in x
    y_range: [0, 100e-9]     # Full width in y
    z_position: -5e-9        # Electrode bottom at z=-5nm (5nm thick: z=0 → z=-5nm)
    voltage: -0.5            # -0.5V

  - name: "finger_gate_2"
    shape: "rectangle"
    x_range: [40e-9, 60e-9]
    y_range: [0, 100e-9]
    z_position: -5e-9        # Electrode bottom at z=-5nm
    voltage: -1.0            # -1.0V

  - name: "finger_gate_3"
    shape: "rectangle"
    x_range: [70e-9, 90e-9]
    y_range: [0, 100e-9]
    z_position: -5e-9        # Electrode bottom at z=-5nm
    voltage: -0.5            # -0.5V

# Boundary conditions
boundary_conditions:
  z_top:
    type: "neumann"                  # Neumann boundary condition
    value: 0.0                       # dphi/dz = 0

  z_bottom:
    type: "dirichlet"                # Dirichlet boundary condition
    value: 0.0                       # dphi/dz = 0

  x_sides:
    type: "periodic"                  # or "neumann"
    value: 0.0

  y_sides:
    type: "periodic"                  # or "neumann"
    value: 0.0
